### ISSUE TITLE
App - Homepage - wire up everything in Vue

### ISSUE THREAD

**Issue by bokova** [Learn-by-doing/hobobar#30]
We don't have the actual homepage wired up using the Vue lib.

**Comment by RobinCsl** [comment]
I found this blog post which could be helpful.
https://onsen.io/blog/onsen-ui-google-maps-javascript-api-v3-angularjs-sample-application/

**Comment by bokova** [comment]
@chill117 there's more on _mounted_ and similar methods at https://vuejs.org/v2/guide/instance.html#Instance-Lifecycle-Hooks

**Comment by chill117** [comment]
We will try using vanilla JS and backbone.
