### ISSUE TITLE
Server - Routes - Create tree

### ISSUE THREAD

**Issue by bokova** [Learn-by-doing/hobobar#4]
Attributes:
* Location
* Type of tree ("cherry", "apple", etc)
* Description
* Image data (about 2 to 10 megabytes depending on the quality of the device's camera)

**Comment by karliatto** [comment]
Should we implement it using a ORM like Bookshelf.js or just create a simple post like below?
```javascript
app.post('/tree/add', function(req, res) {
		app.db('trees')
		.insert({
			latitude : req.body.latitude,
			longitude : req.body.longitude,
			type : req.body.type,
			description : req.body.description,
			filename :  filename,
		})
		.catch(function(error) {
			console.log(error);
		});
	});
```

Then in order to upload the pictures it'll need something for parsing data, I guess we can use something like https://github.com/felixge/node-formidable ??

any suggestions?

**Comment by chill117** [comment]
> Should we implement it using a ORM like Bookshelf.js or just create a simple post like below?

Let's just use knex without bookshelf, like you have done here already.

> Then in order to upload the pictures it'll need something for parsing data, I guess we can use something like https://github.com/felixge/node-formidable ??

[formidable](https://github.com/felixge/node-formidable) looks like it is not being maintained so much. I think [multer](https://github.com/expressjs/multer) might be a better choice for handling file uploads. We can try one of them, and then if there is a problem we can always switch later.

**Comment by bokova** [comment]
I used formidable before so I can even provide an example how to upload files with it should you need some inspiration :) I think I was quite happy with what it did

**Comment by karliatto** [comment]
thanks for the recommendations and inspirations :) I went for [multer](https://github.com/expressjs/multer) and it works fine.
The question now is the following:  is the directory [hobobar/asset/](https://github.com/Learn-by-doing/hobobar/tree/master/assets) meant to be the one for the pictures? or should I create a new one inside [hobobar/server/](https://github.com/Learn-by-doing/hobobar/tree/master/server)?

**Comment by bokova** [comment]
Glad to hear:) 

Assets is not for this. That folder is for things like airframes and other resources.

Use your own folder inside Server instead.

-----Original Message-----
