### ISSUE TITLE
Improve add tree form UI

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/hobobar#55]
Add some basic styling to make the add tree form nicer.

**Comment by karliatto** [comment]
I did some improvements in the form with the pr #66

**Comment by Magwit** [comment]
Hi @karliatto  and thank for the improvement and for letting me know. I was working on my branch to modify the tree form UI a few days ago but got nowhere. It's my first time working anything that looks like Cordova. I'll be working with cordova the next few days to see if I can get somewhere with the tree form UI.

**Comment by karliatto** [comment]
Hi @Magwit, if you look to [my pr](https://github.com/Learn-by-doing/hobobar/pull/66/files) you can see that you don't have to deal with cordova for changing the ui, just html and css.
If you have any doubt do not hesitate to ask here!
